import type { GroundUnitKind, ResourcePool, SpaceUnitKind, UnitDefinition } from '../types';

const cost = (metal: number, crystal: number, gold: number): ResourcePool => ({ metal, crystal, gold });

export const AEGIS_GROUND_KINDS = [
  'aegisWarden', 'aegisBastionTank', 'aegisRampartArtillery', 'aegisPaladinGuard', 'aegisFortressWalker',
] satisfies GroundUnitKind[];

export const AEGIS_SPACE_KINDS = [
  'aegisBastionLander', 'aegisShieldMonitor', 'aegisLanceFrigate', 'aegisSentinelFrigate',
  'aegisBastionCruiser', 'aegisWardCruiser', 'aegisLanceCruiser', 'aegisSentinelCruiser',
  'aegisCitadelCarrier', 'aegisWardBattleship', 'aegisLanceBattleship', 'aegisSentinelBattleship', 'aegisSovereignDreadnought',
] satisfies SpaceUnitKind[];

type AegisUnitKind = typeof AEGIS_GROUND_KINDS[number] | typeof AEGIS_SPACE_KINDS[number];

export const AEGIS_UNITS: Record<AegisUnitKind, UnitDefinition> = {
  aegisWarden: { label: 'Warden Cohort', description: 'Shield-bearing infantry that locks into a protective formation around nearby allies.', cost: cost(58, 25, 12), time: 18, factory: 'ground', hp: 150, shields: 100, range: 15, moveSpeed: 4.8, weapon: { label: 'Triad Pulse Carbines', damage: 1.5, cooldown: .9, projectiles: 3, effect: 'pulse' }, ability: { kind: 'shieldWall', label: 'Shield Wall', description: 'While its shields hold, nearby allied ground units take 20% less damage.' } },
  aegisBastionTank: { label: 'Bastion Tank', description: 'A super-heavy shield tank that hardens its armor whenever it settles into a firing position.', cost: cost(160, 95, 55), time: 40, factory: 'ground', hp: 420, shields: 230, range: 20, moveSpeed: 3.4, weapon: { label: 'Bastion Rail Cannon', damage: 16, cooldown: 1.6, projectiles: 1, effect: 'railgun' }, ability: { kind: 'bastionAnchor', label: 'Anchor Protocol', description: 'Takes 35% less damage while stationary and firing.' } },
  aegisRampartArtillery: { label: 'Rampart Artillery', description: 'A predictive bombardment platform that punishes enemies attempting to reposition.', cost: cost(170, 120, 70), time: 44, factory: 'ground', hp: 250, shields: 170, range: 38, moveSpeed: 2.2, weapon: { label: 'Twin Rampart Bombards', damage: 14, cooldown: 3, projectiles: 2, effect: 'artillery' }, ability: { kind: 'movingTargetBarrage', label: 'Predictive Barrage', description: 'Deals 75% more damage to ground units under a movement order.' } },
  aegisPaladinGuard: { label: 'Paladin Guard', description: 'Elite powered infantry that steps into incoming fire to preserve the formation.', cost: cost(145, 110, 70), time: 38, factory: 'ground', hp: 300, shields: 240, range: 14, moveSpeed: 4, weapon: { label: 'Paired Arc Lances', damage: 5, cooldown: 1.1, projectiles: 2, effect: 'plasma' }, requires: 'groundWarfare', advancedFactory: true, ability: { kind: 'paladinIntercept', label: 'Paladin Intercept', description: 'Absorbs 40% of damage aimed at nearby allied ground units.' } },
  aegisFortressWalker: { label: 'Fortress Walker', description: 'A walking citadel whose impact cannon tears through clustered formations.', cost: cost(390, 300, 200), time: 86, factory: 'ground', hp: 850, shields: 450, range: 42, moveSpeed: 1.7, weapon: { label: 'Judgment Siege Cannon', damage: 52, cooldown: 2.8, projectiles: 1, effect: 'siege' }, requires: 'heavyArmor', advancedFactory: true, ability: { kind: 'judgmentShockwave', label: 'Judgment Shockwave', description: 'Deals 45% splash damage to enemies near the primary target.' } },
  aegisBastionLander: { label: 'Bastion Lander', description: 'A five-squad Tier 1 assault lander built to survive the dangerous final approach.', cost: cost(150, 110, 70), time: 35, factory: 'space', spaceTier: 1, hp: 340, shields: 260, range: 190, moveSpeed: 0, weapon: { label: 'Twin Guardian Lasers', damage: .18, cooldown: .3, projectiles: 2, effect: 'laser' }, capacity: 5, ability: { kind: 'armoredApproach', label: 'Armored Approach', description: 'Takes 45% less damage while landing or embarking ground forces.' } },
  aegisShieldMonitor: { label: 'Shield Monitor', description: 'A Tier 1 fleet-support frigate that projects its shield envelope over nearby warships.', cost: cost(210, 160, 95), time: 42, factory: 'space', spaceTier: 1, hp: 420, shields: 380, range: 300, moveSpeed: 0, weapon: { label: 'Triune Beam Array', damage: .55, cooldown: .45, projectiles: 3, effect: 'laser' }, ability: { kind: 'shieldProjection', label: 'Shield Projection', description: 'Nearby allied ships regenerate 10 extra shield per second and take 30% less damage.' } },
  aegisLanceFrigate: { label: 'Lance Frigate', description: 'A Tier 1 standoff sniper whose axial rail lance gains power across open orbit.', cost: cost(230, 180, 110), time: 48, factory: 'space', spaceTier: 1, hp: 350, shields: 260, range: 500, moveSpeed: 0, weapon: { label: 'Spearpoint Rail Lance', damage: 22, cooldown: 3, projectiles: 1, effect: 'railgun' }, ability: { kind: 'rangeCalibration', label: 'Range Calibration', description: 'Deals up to 70% more damage based on distance to its target.' } },
  aegisBastionCruiser: { label: 'Bastion Transport Cruiser', description: 'The Tier 2 Bastion Lander successor, carrying eight squads behind cruiser-grade shields.', cost: cost(500, 390, 245), time: 79, factory: 'space', spaceTier: 2, hp: 780, shields: 720, range: 260, moveSpeed: 0, weapon: { label: 'Bastion Cruiser Defense Grid', damage: .65, cooldown: .45, projectiles: 4, effect: 'laser' }, requires: 'orbitalEngineering', capacity: 8, ability: { kind: 'armoredApproach', label: 'Armored Approach', description: 'Takes 45% less damage while landing or embarking ground forces.' } },
  aegisWardCruiser: { label: 'Ward Cruiser', description: 'A Tier 2 line cruiser that improves on frigate shielding and interposes itself between attackers and allies.', cost: cost(480, 360, 230), time: 76, factory: 'space', spaceTier: 2, hp: 850, shields: 700, range: 380, moveSpeed: 0, weapon: { label: 'Quad Ward Batteries', damage: 4, cooldown: 1.1, projectiles: 4, effect: 'plasma' }, requires: 'orbitalEngineering', ability: { kind: 'wardInterception', label: 'Ward Interception', description: 'Draws hostile ship volleys away from nearby allied ships.' } },
  aegisLanceCruiser: { label: 'Lance Cruiser', description: 'The Tier 2 Lance Frigate successor, pairing long-range rail lances on a fortified cruiser hull.', cost: cost(510, 400, 255), time: 82, factory: 'space', spaceTier: 2, hp: 720, shields: 650, range: 540, moveSpeed: 0, weapon: { label: 'Twin Spearpoint Rail Lances', damage: 25, cooldown: 2.7, projectiles: 2, effect: 'railgun' }, requires: 'orbitalEngineering', ability: { kind: 'rangeCalibration', label: 'Range Calibration', description: 'Deals up to 70% more damage based on distance to its target.' } },
  aegisSentinelCruiser: { label: 'Sentinel Flak Cruiser', description: 'The Tier 2 Sentinel Frigate successor, projecting a precise cruiser-scale interceptor screen.', cost: cost(520, 410, 260), time: 84, factory: 'space', spaceTier: 2, hp: 800, shields: 680, range: 380, moveSpeed: 0, weapon: { label: 'Sentinel Cruiser Flak Matrix', damage: 1.1, cooldown: .5, projectiles: 7, effect: 'laser' }, requires: 'orbitalEngineering', ability: { kind: 'antiFighterCannons', label: 'Sentinel Cruiser Screen', description: 'Prioritizes one hostile fighter wing and deals 50% more damage to fighters.' } },
  aegisCitadelCarrier: { label: 'Citadel Mega-Carrier', description: 'A Tier 3 mobile fortress launching armored interceptors while its construction drones repair the fleet.', cost: cost(900, 720, 480), time: 130, factory: 'space', spaceTier: 3, hp: 1450, shields: 1250, range: 380, moveSpeed: 0, weapon: { label: 'Sentinel Interceptor Wing', damage: 2, cooldown: .9, projectiles: 8, effect: 'drone' }, requires: 'carrierOperations', capacity: 12, fighterWing: { label: 'Sentinel Interceptors', capacity: 8, rebuildTime: 22, attritionTime: 20 }, ability: { kind: 'repairDrones', label: 'Repair Drones', description: 'Restores 6 hull per second to nearby allied ships during orbital combat.' } },
  aegisSentinelFrigate: { label: 'Sentinel Flak Frigate', description: 'A compact Tier 1 shield escort whose precise emitters track hostile strike craft.', cost: cost(340, 250, 160), time: 52, factory: 'space', spaceTier: 1, hp: 400, shields: 400, range: 320, moveSpeed: 0, weapon: { label: 'Sentinel Flak Emitters', damage: .45, cooldown: .4, projectiles: 4, effect: 'laser' }, ability: { kind: 'antiFighterCannons', label: 'Sentinel Screen', description: 'Prioritizes one hostile fighter wing and deals 50% more damage to fighters.' } },
  aegisWardBattleship: { label: 'Ward Battleship', description: 'The Tier 3 shield-line apex, replacing an upgraded escort cruiser with a true fleet battleship.', cost: cost(1020, 800, 520), time: 138, factory: 'space', spaceTier: 3, hp: 1750, shields: 1500, range: 440, moveSpeed: 0, weapon: { label: 'Grand Ward Batteries', damage: 8, cooldown: 1.1, projectiles: 4, effect: 'plasma' }, requires: 'capitalShips', ability: { kind: 'wardInterception', label: 'Grand Ward Interception', description: 'Draws hostile ship volleys away from nearby allied ships.' } },
  aegisLanceBattleship: { label: 'Lance Battleship', description: 'The Tier 3 lance-line apex, mounting three capital rail lances behind fortress shields.', cost: cost(1080, 850, 550), time: 144, factory: 'space', spaceTier: 3, hp: 1600, shields: 1450, range: 570, moveSpeed: 0, weapon: { label: 'Triune Capital Rail Lances', damage: 34, cooldown: 2.5, projectiles: 3, effect: 'railgun' }, requires: 'capitalShips', ability: { kind: 'rangeCalibration', label: 'Capital Range Calibration', description: 'Deals up to 70% more damage based on distance to its target.' } },
  aegisSentinelBattleship: { label: 'Sentinel Flak Battleship', description: 'The Tier 3 sentinel-line apex, protecting an entire fleet with layered capital flak emitters.', cost: cost(1050, 830, 535), time: 141, factory: 'space', spaceTier: 3, hp: 1800, shields: 1500, range: 450, moveSpeed: 0, weapon: { label: 'Sovereign Sentinel Curtain', damage: 2.5, cooldown: .65, projectiles: 10, effect: 'laser' }, requires: 'capitalShips', ability: { kind: 'antiFighterCannons', label: 'Sovereign Sentinel Screen', description: 'Prioritizes one hostile fighter wing and deals 50% more damage to fighters.' } },
  aegisSovereignDreadnought: { label: 'Sovereign Titan', description: 'The Directorate’s unique Tier 3 Titan fortress, built to erase tightly packed fleets.', cost: cost(1400, 1100, 800), time: 180, factory: 'space', spaceTier: 3, hp: 2600, shields: 2100, range: 500, moveSpeed: 0, weapon: { label: 'Sovereign Siege Matrix', damage: 15, cooldown: 1.2, projectiles: 4, effect: 'siege' }, requires: 'titanEngineering', ability: { kind: 'sovereignBarrage', label: 'Sovereign Barrage', description: 'Each salvo deals 35% damage to every hostile ship near its primary target.' } },
};
