import type { GroundUnitKind, ResourcePool, SpaceUnitKind, UnitDefinition } from '../types';

const cost = (metal: number, crystal: number, gold: number): ResourcePool => ({ metal, crystal, gold });

export const AEGIS_GROUND_KINDS = [
  'aegisWarden', 'aegisBastionTank', 'aegisRampartArtillery', 'aegisSkyguard', 'aegisSeraphSkimmer', 'aegisHaloGunship', 'aegisPaladinGuard', 'aegisFortressWalker',
] satisfies GroundUnitKind[];

export const AEGIS_SPACE_KINDS = [
  'aegisBastionLander', 'aegisShieldMonitor', 'aegisLanceFrigate', 'aegisSentinelFrigate', 'aegisFarcastScout', 'aegisResonanceAnchor',
  'aegisBastionLanderII', 'aegisShieldMonitorII', 'aegisLanceCruiser', 'aegisSentinelCruiser', 'aegisAnchorCruiser',
  'aegisCitadelCarrier', 'aegisSovereignDreadnought',
] satisfies SpaceUnitKind[];

type AegisUnitKind = typeof AEGIS_GROUND_KINDS[number] | typeof AEGIS_SPACE_KINDS[number] | 'aegisWardCruiser';

export const AEGIS_UNITS: Record<AegisUnitKind, UnitDefinition> = {
  aegisWarden: { label: 'Warden Cohort', description: 'Shield-bearing infantry that locks into a protective formation around nearby allies.', cost: cost(58, 25, 12), time: 18, factory: 'ground', hp: 150, shields: 100, range: 15, moveSpeed: 4.8, weapon: { label: 'Triad Pulse Carbines', damage: 1.5, cooldown: .9, projectiles: 3, effect: 'pulse' }, ability: { kind: 'shieldWall', label: 'Shield Wall', description: 'While its shields hold, nearby allied ground units take 20% less damage.' } },
  aegisBastionTank: { label: 'Bastion Tank', description: 'A super-heavy shield tank that hardens its armor whenever it settles into a firing position.', cost: cost(160, 95, 55), time: 40, factory: 'ground', hp: 420, shields: 230, range: 20, moveSpeed: 3.4, groundTargeting: 'surface', weapon: { label: 'Bastion Rail Cannon', damage: 16, cooldown: 1.6, projectiles: 1, effect: 'railgun' }, ability: { kind: 'bastionAnchor', label: 'Anchor Protocol', description: 'Takes 35% less damage while stationary and firing.' } },
  aegisRampartArtillery: { label: 'Rampart Artillery', description: 'A predictive bombardment platform that punishes enemies attempting to reposition.', cost: cost(170, 120, 70), time: 44, factory: 'ground', hp: 250, shields: 170, range: 38, moveSpeed: 2.2, weapon: { label: 'Twin Rampart Bombards', damage: 14, cooldown: 3, projectiles: 2, effect: 'artillery' }, ability: { kind: 'movingTargetBarrage', label: 'Predictive Barrage', description: 'Deals 75% more damage to ground units under a movement order.' } },
  aegisSkyguard: { label: 'Skyguard Array', description: 'A shielded mobile flak array that shreds airborne threats and exposed infantry.', cost: cost(140, 100, 60), time: 32, factory: 'ground', hp: 230, shields: 180, range: 22, moveSpeed: 5.5, weapon: { label: 'Precision Flak Emitters', damage: 1.1, cooldown: .65, projectiles: 3, effect: 'laser' }, ability: { kind: 'groundFlak', label: 'Skyguard Tracking', description: 'Deals 50% more damage to infantry and flying ground units.' } },
  aegisSeraphSkimmer: { label: 'Seraph Skimmer', description: 'A swift shielded skimmer whose elevated sensor choir reveals a wide area.', cost: cost(110, 82, 48), time: 28, factory: 'ground', hp: 170, shields: 150, range: 16, visionRange: 42, moveSpeed: 13, flying: true, weapon: { label: 'Seraph Beam', damage: 1.4, cooldown: .55, projectiles: 2, effect: 'laser' }, ability: { kind: 'aerialRecon', label: 'Seraphic Survey', description: 'Flies over rocks and reveals a much wider area than line units.' } },
  aegisHaloGunship: { label: 'Halo Gunship', description: 'A shield-heavy bomber that crosses terrain to strike exposed surface formations at range.', cost: cost(230, 175, 110), time: 54, factory: 'ground', hp: 390, shields: 320, range: 27, visionRange: 32, moveSpeed: 7, flying: true, groundTargeting: 'surface', weapon: { label: 'Twin Halo Lances', damage: 8, cooldown: 1.35, projectiles: 2, effect: 'plasma' }, requires: 'groundWarfare', advancedFactory: true, ability: { kind: 'airSupport', label: 'Halo Air Support', description: 'Flies over rocks, ignores forest cover, and attacks surface targets only.' } },
  aegisPaladinGuard: { label: 'Paladin Guard', description: 'Elite powered infantry that steps into incoming fire to preserve the formation.', cost: cost(145, 110, 70), time: 38, factory: 'ground', hp: 300, shields: 240, range: 14, moveSpeed: 4, weapon: { label: 'Paired Arc Lances', damage: 5, cooldown: 1.1, projectiles: 2, effect: 'plasma' }, requires: 'groundWarfare', advancedFactory: true, ability: { kind: 'paladinIntercept', label: 'Paladin Intercept', description: 'Absorbs 40% of damage aimed at nearby allied ground units.' } },
  aegisFortressWalker: { label: 'Fortress Walker', description: 'A walking citadel whose impact cannon tears through clustered surface formations.', cost: cost(390, 300, 200), time: 86, factory: 'ground', hp: 850, shields: 450, range: 42, moveSpeed: 1.7, groundTargeting: 'surface', weapon: { label: 'Judgment Siege Cannon', damage: 52, cooldown: 2.8, projectiles: 1, effect: 'siege' }, requires: 'heavyArmor', advancedFactory: true, ability: { kind: 'judgmentShockwave', label: 'Judgment Shockwave', description: 'Deals 45% splash damage to enemies near the primary target.' } },
  aegisBastionLander: { label: 'Bastion Lander', description: 'A five-squad Tier 1 assault lander built to survive the dangerous final approach.', cost: cost(150, 110, 70), time: 35, factory: 'space', spaceTier: 1, hp: 340, shields: 260, range: 190, moveSpeed: 0, weapon: { label: 'Guardian Laser', damage: .18, cooldown: .3, projectiles: 2, effect: 'laser' }, capacity: 5, ability: { kind: 'armoredApproach', label: 'Armored Approach', description: 'Takes 45% less damage while landing or embarking ground forces.' } },
  aegisShieldMonitor: { label: 'Shield Monitor', description: 'A Tier 1 fleet-support frigate that projects its shield envelope over nearby warships.', cost: cost(210, 160, 95), time: 42, factory: 'space', spaceTier: 1, hp: 420, shields: 380, range: 300, moveSpeed: 0, weapon: { label: 'Triune Beam Emitter', damage: .55, cooldown: .45, projectiles: 3, effect: 'laser' }, ability: { kind: 'shieldProjection', label: 'Shield Projection', description: 'Nearby allied ships regenerate 10 extra shield per second and take 30% less damage.' } },
  aegisLanceFrigate: { label: 'Lance Frigate', description: 'A Tier 1 standoff sniper whose axial rail lance gains power across open orbit.', cost: cost(230, 180, 110), time: 48, factory: 'space', spaceTier: 1, hp: 350, shields: 260, range: 500, moveSpeed: 0, weapon: { label: 'Spearpoint Rail Lance', damage: 22, cooldown: 3, projectiles: 1, effect: 'railgun' }, ability: { kind: 'rangeCalibration', label: 'Range Calibration', description: 'Deals up to 70% more damage based on distance to its target.' } },
  aegisFarcastScout: { label: 'Farcast Scout', description: 'A lightly armed Tier 1 scout wrapped around an exceptionally powerful transit drive.', cost: cost(160, 120, 75), time: 10, factory: 'space', spaceTier: 1, hp: 230, shields: 260, range: 220, moveSpeed: 0, orbitSpeedMultiplier: 2.5, weapon: { label: 'Farcast Survey Beam', damage: .18, cooldown: .8, projectiles: 1, effect: 'laser' }, ability: { kind: 'reconDrive', label: 'Farcast Drive', description: 'Moves through gravity wells and phase lanes at 2.5× normal ship speed, but carries only a light defensive beam.' } },
  aegisResonanceAnchor: { label: 'Resonance Anchor', description: 'A Tier 1 control frigate that drags hostile drives and firing cycles out of resonance.', cost: cost(280, 210, 130), time: 50, factory: 'space', spaceTier: 1, hp: 420, shields: 430, range: 350, moveSpeed: 0, weapon: { label: 'Resonance Beam', damage: .3, cooldown: .8, projectiles: 2, effect: 'laser' }, ability: { kind: 'phaseControl', label: 'Resonance Drag', description: 'Enemies inside range move and fire at 75% speed. Multiple fields stack multiplicatively.' } },
  aegisBastionLanderII: { label: 'Bastion Lander Cruiser', description: 'Tier 2 counterpart to the Bastion Lander, carrying ten squads behind layered shields.', cost: cost(360, 280, 180), time: 64, factory: 'space', spaceTier: 2, hp: 680, shields: 520, range: 230, moveSpeed: 0, weapon: { label: 'Bastion II Guardian Laser', damage: .24, cooldown: .3, projectiles: 4, effect: 'laser' }, capacity: 10, requires: 'orbitalEngineering', ability: { kind: 'armoredApproach', label: 'Reinforced Approach', description: 'Takes 45% less damage while landing or embarking ground forces.' } },
  aegisShieldMonitorII: { label: 'Shield Monitor Cruiser', description: 'Tier 2 counterpart to the Shield Monitor with five beam emitters and a cruiser-scale envelope.', cost: cost(470, 360, 230), time: 72, factory: 'space', spaceTier: 2, hp: 840, shields: 760, range: 360, moveSpeed: 0, weapon: { label: 'Monitor II Beam Emitter', damage: .75, cooldown: .45, projectiles: 5, effect: 'laser' }, requires: 'orbitalEngineering', ability: { kind: 'shieldProjection', label: 'Cruiser Shield Projection', description: 'Nearby allied ships regenerate 10 extra shield per second and take 30% less damage.' } },
  aegisLanceCruiser: { label: 'Lance Cruiser', description: 'Tier 2 counterpart to the Lance Frigate with paired calibrated rail lances.', cost: cost(500, 390, 250), time: 78, factory: 'space', spaceTier: 2, hp: 700, shields: 520, range: 540, moveSpeed: 0, weapon: { label: 'Lance Cruiser Rail Lance', damage: 24, cooldown: 3, projectiles: 2, effect: 'railgun' }, requires: 'orbitalEngineering', ability: { kind: 'rangeCalibration', label: 'Cruiser Range Calibration', description: 'Deals up to 70% more damage based on distance to its target.' } },
  aegisSentinelCruiser: { label: 'Sentinel Flak Cruiser', description: 'Tier 2 counterpart to the Sentinel Flak Frigate with six precision tracking emitters.', cost: cost(520, 400, 260), time: 82, factory: 'space', spaceTier: 2, hp: 800, shields: 800, range: 370, moveSpeed: 0, weapon: { label: 'Sentinel Cruiser Flak Emitter', damage: .65, cooldown: .4, projectiles: 6, effect: 'laser' }, requires: 'orbitalEngineering', ability: { kind: 'antiFighterCannons', label: 'Sentinel Cruiser Screen', description: 'Prioritizes one hostile fighter wing and deals 50% more damage to fighters.' } },
  aegisAnchorCruiser: { label: 'Resonance Anchor Cruiser', description: 'Tier 2 counterpart to the Resonance Anchor, powerful enough to hold hostile ships outside phase lanes.', cost: cost(600, 470, 310), time: 88, factory: 'space', spaceTier: 2, hp: 840, shields: 860, range: 410, moveSpeed: 0, weapon: { label: 'Anchor Resonance Array', damage: .45, cooldown: .8, projectiles: 4, effect: 'laser' }, requires: 'orbitalEngineering', ability: { kind: 'phaseControl', label: 'Resonance Interdiction', description: 'Enemies inside range move and fire at 75% speed and cannot enter a phase lane. Multiple fields stack multiplicatively.' } },
  aegisWardCruiser: { label: 'Ward Cruiser', description: 'A Tier 2 line cruiser that improves on frigate shielding and interposes itself between attackers and allies.', cost: cost(480, 360, 230), time: 76, factory: 'space', spaceTier: 2, hp: 850, shields: 700, range: 380, moveSpeed: 0, weapon: { label: 'Ward Plasma Battery', damage: 4, cooldown: 1.1, projectiles: 4, effect: 'plasma' }, requires: 'orbitalEngineering', ability: { kind: 'wardInterception', label: 'Ward Interception', description: 'Draws hostile ship volleys away from nearby allied ships.' } },
  aegisCitadelCarrier: { label: 'Citadel Mega-Carrier', description: 'A Tier 3 mobile fortress launching armored interceptors while its construction drones repair the fleet.', cost: cost(900, 720, 480), time: 130, factory: 'space', spaceTier: 3, hp: 1450, shields: 1250, range: 380, moveSpeed: 0, weapon: { label: 'Sentinel Interceptor', damage: 2, cooldown: .9, projectiles: 8, effect: 'drone' }, requires: 'carrierOperations', capacity: 12, fighterWing: { label: 'Sentinel Interceptors', capacity: 8, rebuildTime: 22, attritionTime: 20 }, ability: { kind: 'repairDrones', label: 'Repair Drones', description: 'Restores 6 hull per second to nearby allied ships during orbital combat.' } },
  aegisSentinelFrigate: { label: 'Sentinel Flak Frigate', description: 'A compact Tier 1 shield escort whose precise emitters track hostile strike craft.', cost: cost(340, 250, 160), time: 52, factory: 'space', spaceTier: 1, hp: 400, shields: 400, range: 320, moveSpeed: 0, weapon: { label: 'Sentinel Flak Emitter', damage: .45, cooldown: .4, projectiles: 4, effect: 'laser' }, ability: { kind: 'antiFighterCannons', label: 'Sentinel Screen', description: 'Prioritizes one hostile fighter wing and deals 50% more damage to fighters.' } },
  aegisSovereignDreadnought: { label: 'Sovereign Titan', description: 'The Directorate’s unique Tier 3 Titan fortress, built to erase tightly packed fleets.', cost: cost(1400, 1100, 800), time: 180, factory: 'space', spaceTier: 3, hp: 2600, shields: 2100, range: 500, moveSpeed: 0, weapon: { label: 'Sovereign Siege Projector', damage: 15, cooldown: 1.2, projectiles: 4, effect: 'siege' }, requires: 'titanEngineering', ability: { kind: 'sovereignBarrage', label: 'Sovereign Barrage', description: 'Each salvo deals 35% damage to every hostile ship near its primary target.' } },
};
