import type { GroundUnitKind, ResourcePool, SpaceUnitKind, UnitDefinition } from '../types';

const cost = (metal: number, crystal: number, gold: number): ResourcePool => ({ metal, crystal, gold });

export const COVENANT_GROUND_KINDS = [
  'covenantCohort', 'covenantBastionStrider', 'covenantFurnaceArtillery', 'covenantRepairDrone', 'covenantJuggernaut',
] satisfies GroundUnitKind[];

export const COVENANT_SPACE_KINDS = [
  'covenantAssemblyArk', 'covenantSalvageFrigate', 'covenantChainFrigate', 'covenantFoundryCruiser',
  'covenantFabricatorCarrier', 'covenantIronclad', 'covenantDreadforge',
] satisfies SpaceUnitKind[];

type CovenantUnitKind = typeof COVENANT_GROUND_KINDS[number] | typeof COVENANT_SPACE_KINDS[number] | 'covenantBulwark';

export const COVENANT_UNITS: Record<CovenantUnitKind, UnitDefinition> = {
  covenantCohort: { label: 'Iron Cohort', description: 'Networked combat automatons that combine unlike weapon modules into a stronger firing solution.', cost: cost(44, 18, 8), time: 13, factory: 'ground', hp: 165, shields: 0, range: 15, moveSpeed: 6.4, weapon: { label: 'Linked Pulse Carbines', damage: 1.2, cooldown: .8, projectiles: 3, effect: 'pulse' }, ability: { kind: 'modularTargeting', label: 'Modular Targeting', description: 'Deals 25% more damage while a different Covenant ground chassis is nearby.' } },
  covenantBastionStrider: { label: 'Bastion Strider', description: 'A quadruped gun platform whose outer plates absorb the opening punishment of an engagement.', cost: cost(120, 64, 32), time: 30, factory: 'ground', hp: 390, shields: 20, range: 20, moveSpeed: 4.2, weapon: { label: 'Bastion Kinetic Cannon', damage: 15, cooldown: 1.6, projectiles: 1, effect: 'kinetic' }, ability: { kind: 'ablativePlating', label: 'Ablative Plating', description: 'Takes 30% less damage while above half hull.' } },
  covenantFurnaceArtillery: { label: 'Furnace Artillery', description: 'An industrial bombardment chassis firing superheated penetrators through shield screens.', cost: cost(135, 82, 46), time: 34, factory: 'ground', hp: 220, shields: 10, range: 36, moveSpeed: 2.8, weapon: { label: 'Furnace Driver', damage: 24, cooldown: 2.7, projectiles: 1, effect: 'artillery' }, ability: { kind: 'shieldBreaker', label: 'Shield Breaker', description: 'Deals 50% more damage while its ground target still has shields.' } },
  covenantRepairDrone: { label: 'Repair Drone', description: 'A mobile maintenance intelligence that restores nearby machines without interrupting their fire.', cost: cost(105, 78, 42), time: 29, factory: 'ground', hp: 170, shields: 35, range: 12, moveSpeed: 8, weapon: { label: 'Twin Cutting Lasers', damage: .45, cooldown: .45, projectiles: 2, effect: 'laser' }, requires: 'groundWarfare', advancedFactory: true, ability: { kind: 'fieldRepair', label: 'Field Repair', description: 'Restores 1 hull per second to nearby allied ground machines.' } },
  covenantJuggernaut: { label: 'Juggernaut Engine', description: 'A six-legged siege foundry whose impact round fractures whole defensive lines.', cost: cost(340, 230, 145), time: 76, factory: 'ground', hp: 900, shields: 60, range: 40, moveSpeed: 1.9, weapon: { label: 'Forgequake Cannon', damage: 50, cooldown: 2.6, projectiles: 1, effect: 'siege' }, requires: 'heavyArmor', advancedFactory: true, ability: { kind: 'forgeShockwave', label: 'Forge Shockwave', description: 'Deals 40% splash damage to enemies near the primary target.' } },
  covenantBulwark: { label: 'Iron Bulwark', description: 'A self-maintaining twin-cannon emplacement that repairs nearby defensive machines.', cost: cost(0, 0, 0), factory: 'ground', hp: 460, shields: 30, range: 35, moveSpeed: 0, weapon: { label: 'Twin Foundry Cannons', damage: 5.5, cooldown: 1, projectiles: 2, effect: 'kinetic' }, ability: { kind: 'fieldRepair', label: 'Bulwark Repair Field', description: 'Restores 1 hull per second to nearby allied ground machines.' } },
  covenantAssemblyArk: { label: 'Assembly Ark', description: 'A six-squad landing ship whose mobile machine shops rebuild nearby hulls.', cost: cost(135, 88, 44), time: 28, factory: 'space', hp: 360, shields: 70, range: 180, moveSpeed: 0, weapon: { label: 'Assembly Defense Lasers', damage: .2, cooldown: .3, projectiles: 2, effect: 'laser' }, capacity: 6, ability: { kind: 'assemblyLine', label: 'Mobile Assembly Line', description: 'Restores 4 hull per second to nearby allied ships during orbital combat.' } },
  covenantSalvageFrigate: { label: 'Salvage Frigate', description: 'A recovery warship that strips battle wreckage into immediately usable metal.', cost: cost(145, 82, 38), time: 29, factory: 'space', hp: 320, shields: 65, range: 260, moveSpeed: 0, weapon: { label: 'Grapple Lasers', damage: .7, cooldown: .45, projectiles: 2, effect: 'laser' }, ability: { kind: 'salvageArray', label: 'Salvage Array', description: 'Increases Covenant metal recovered from orbital casualties by 50% if it survives.' } },
  covenantChainFrigate: { label: 'Chain Frigate', description: 'A linked-cannon hunter that concentrates fire on already compromised hulls.', cost: cost(175, 108, 58), time: 36, factory: 'space', hp: 310, shields: 55, range: 410, moveSpeed: 0, weapon: { label: 'Triple Chain Drivers', damage: 4.2, cooldown: 1.2, projectiles: 3, effect: 'kinetic' }, ability: { kind: 'focusFire', label: 'Failure Cascade', description: 'Deals 50% more damage to ships whose hull is already damaged.' } },
  covenantFoundryCruiser: { label: 'Foundry Cruiser', description: 'An industrial line cruiser carrying repair gantries for an entire battle group.', cost: cost(430, 300, 180), time: 68, factory: 'space', hp: 880, shields: 140, range: 350, moveSpeed: 0, weapon: { label: 'Foundry Plasma Banks', damage: 3.2, cooldown: 1, projectiles: 4, effect: 'plasma' }, requires: 'orbitalEngineering', ability: { kind: 'foundryAura', label: 'Fleet Foundry', description: 'Restores 7 hull per second to nearby allied ships during orbital combat.' } },
  covenantFabricatorCarrier: { label: 'Fabricator Carrier', description: 'A modular carrier that replaces destroyed attack drones as quickly as it launches them.', cost: cost(650, 470, 280), time: 96, factory: 'space', hp: 1120, shields: 180, range: 330, moveSpeed: 0, weapon: { label: 'Fabricated Drone Wing', damage: 1.7, cooldown: .75, projectiles: 6, effect: 'drone' }, requires: 'carrierOperations', advancedFactory: true, capacity: 8, ability: { kind: 'fabricatorSwarm', label: 'Fabricator Swarm', description: 'Every volley also attacks a second nearby hostile ship for 50% damage.' } },
  covenantIronclad: { label: 'Ironclad Battleship', description: 'A capital machine wrapped in replaceable armor blocks and heavy kinetic batteries.', cost: cost(820, 590, 370), time: 122, factory: 'space', hp: 1750, shields: 220, range: 420, moveSpeed: 0, weapon: { label: 'Ironclad Rail Batteries', damage: 9, cooldown: 1.15, projectiles: 3, effect: 'railgun' }, requires: 'capitalShips', advancedFactory: true, ability: { kind: 'ironcladArmor', label: 'Layered Ironclad', description: 'Reduces all incoming damage by 25%.' } },
  covenantDreadforge: { label: 'Dreadforge Titan', description: 'The Covenant apex foundry, built around a beam that dismantles fortresses at the molecular level.', cost: cost(1350, 980, 680), time: 170, factory: 'space', hp: 2900, shields: 320, range: 500, moveSpeed: 0, weapon: { label: 'Dreadforge Dismantler', damage: 18, cooldown: 1.2, projectiles: 3, effect: 'siege' }, requires: 'titanEngineering', advancedFactory: true, ability: { kind: 'dismantlerBeam', label: 'Dismantler Beam', description: 'Deals double damage to orbital defense platforms.' } },
};
