import type { GroundUnitKind, ResourcePool, SpaceUnitKind, UnitDefinition } from '../types';

const cost = (metal: number, crystal: number, gold: number): ResourcePool => ({ metal, crystal, gold });

export const COVENANT_GROUND_KINDS = [
  'covenantCohort', 'covenantBastionStrider', 'covenantFurnaceArtillery', 'covenantFlakEngine', 'covenantWaspDrone', 'covenantFurnaceGunship', 'covenantRepairDrone', 'covenantJuggernaut',
] satisfies GroundUnitKind[];

export const COVENANT_SPACE_KINDS = [
  'covenantAssemblyArk', 'covenantSalvageFrigate', 'covenantChainFrigate', 'covenantInterdictor', 'covenantSurveyorSkiff', 'covenantLockstepFrigate',
  'covenantAssemblyArkII', 'covenantSalvageCruiser', 'covenantChainCruiser', 'covenantInterdictorCruiser', 'covenantLockstepCruiser',
  'covenantFabricatorCarrier', 'covenantIronclad', 'covenantDreadforge',
] satisfies SpaceUnitKind[];

type CovenantUnitKind = typeof COVENANT_GROUND_KINDS[number] | typeof COVENANT_SPACE_KINDS[number] | 'covenantBulwark' | 'covenantFoundryCruiser';

export const COVENANT_UNITS: Record<CovenantUnitKind, UnitDefinition> = {
  covenantCohort: { label: 'Iron Cohort', description: 'Networked combat automatons that combine unlike weapon modules into a stronger firing solution.', cost: cost(44, 18, 8), time: 13, factory: 'ground', hp: 165, shields: 0, range: 15, moveSpeed: 6.4, weapon: { label: 'Linked Pulse Carbines', damage: 1.2, cooldown: .8, projectiles: 3, effect: 'pulse' }, ability: { kind: 'modularTargeting', label: 'Modular Targeting', description: 'Deals 25% more damage while a different Covenant ground chassis is nearby.' } },
  covenantBastionStrider: { label: 'Bastion Strider', description: 'A quadruped gun platform whose outer plates absorb the opening punishment of an engagement.', cost: cost(120, 64, 32), time: 30, factory: 'ground', hp: 390, shields: 20, range: 20, moveSpeed: 4.2, groundTargeting: 'surface', weapon: { label: 'Bastion Kinetic Cannon', damage: 15, cooldown: 1.6, projectiles: 1, effect: 'kinetic' }, ability: { kind: 'ablativePlating', label: 'Ablative Plating', description: 'Takes 30% less damage while above half hull.' } },
  covenantFurnaceArtillery: { label: 'Furnace Artillery', description: 'An industrial bombardment chassis firing superheated penetrators through shield screens.', cost: cost(135, 82, 46), time: 34, factory: 'ground', hp: 220, shields: 10, range: 36, moveSpeed: 2.8, weapon: { label: 'Furnace Driver', damage: 24, cooldown: 2.7, projectiles: 1, effect: 'artillery' }, ability: { kind: 'shieldBreaker', label: 'Shield Breaker', description: 'Deals 50% more damage while its ground target still has shields.' } },
  covenantFlakEngine: { label: 'Flak Engine', description: 'A tracked interception machine that saturates aircraft and infantry with predictive rotary fire.', cost: cost(120, 70, 35), time: 28, factory: 'ground', hp: 280, shields: 15, range: 20, moveSpeed: 5.8, weapon: { label: 'Predictive Rotary Banks', damage: .65, cooldown: .55, projectiles: 5, effect: 'kinetic' }, ability: { kind: 'groundFlak', label: 'Interception Logic', description: 'Deals 50% more damage to infantry and flying ground units.' } },
  covenantWaspDrone: { label: 'Wasp Drone', description: 'An expendable aerial survey machine with wide-spectrum battlefield sensors.', cost: cost(88, 54, 25), time: 22, factory: 'ground', hp: 125, shields: 15, range: 14, visionRange: 40, moveSpeed: 14, flying: true, weapon: { label: 'Wasp Cutting Laser', damage: .6, cooldown: .45, projectiles: 2, effect: 'laser' }, ability: { kind: 'aerialRecon', label: 'Aerial Survey Logic', description: 'Flies over rocks and reveals a much wider area than line machines.' } },
  covenantFurnaceGunship: { label: 'Furnace Gunship', description: 'A modular aerial bomber that carries a rotary cannon over impassable terrain.', cost: cost(210, 132, 72), time: 50, factory: 'ground', hp: 420, shields: 25, range: 24, visionRange: 30, moveSpeed: 6.5, flying: true, groundTargeting: 'surface', weapon: { label: 'Furnace Rotary Cannon', damage: 1.8, cooldown: .5, projectiles: 4, effect: 'kinetic' }, requires: 'groundWarfare', advancedFactory: true, ability: { kind: 'airSupport', label: 'Aerial Fire Platform', description: 'Flies over rocks, ignores forest cover, and attacks surface targets only.' } },
  covenantRepairDrone: { label: 'Repair Drone', description: 'A mobile maintenance intelligence that restores nearby machines without interrupting their fire.', cost: cost(105, 78, 42), time: 29, factory: 'ground', hp: 170, shields: 35, range: 12, moveSpeed: 8, weapon: { label: 'Twin Cutting Lasers', damage: .45, cooldown: .45, projectiles: 2, effect: 'laser' }, requires: 'groundWarfare', advancedFactory: true, ability: { kind: 'fieldRepair', label: 'Field Repair', description: 'Restores 1 hull per second to nearby allied ground machines.' } },
  covenantJuggernaut: { label: 'Juggernaut Engine', description: 'A six-legged siege foundry whose impact round fractures whole surface lines.', cost: cost(340, 230, 145), time: 76, factory: 'ground', hp: 900, shields: 60, range: 40, moveSpeed: 1.9, groundTargeting: 'surface', weapon: { label: 'Forgequake Cannon', damage: 50, cooldown: 2.6, projectiles: 1, effect: 'siege' }, requires: 'heavyArmor', advancedFactory: true, ability: { kind: 'forgeShockwave', label: 'Forge Shockwave', description: 'Deals 40% splash damage to enemies near the primary target.' } },
  covenantBulwark: { label: 'Iron Bulwark', description: 'A self-maintaining twin-cannon emplacement that repairs nearby defensive machines.', cost: cost(0, 0, 0), factory: 'ground', hp: 460, shields: 30, range: 35, moveSpeed: 0, weapon: { label: 'Twin Foundry Cannons', damage: 5.5, cooldown: 1, projectiles: 2, effect: 'kinetic' }, ability: { kind: 'fieldRepair', label: 'Bulwark Repair Field', description: 'Restores 1 hull per second to nearby allied ground machines.' } },
  covenantAssemblyArk: { label: 'Assembly Ark', description: 'A six-squad Tier 1 landing ship whose mobile machine shops rebuild nearby hulls.', cost: cost(135, 88, 44), time: 28, factory: 'space', spaceTier: 1, hp: 360, shields: 70, range: 180, moveSpeed: 0, weapon: { label: 'Assembly Defense Laser', damage: .2, cooldown: .3, projectiles: 2, effect: 'laser' }, capacity: 6, ability: { kind: 'assemblyLine', label: 'Mobile Assembly Line', description: 'Restores 4 hull per second to nearby allied ships during orbital combat.' } },
  covenantSalvageFrigate: { label: 'Salvage Frigate', description: 'A Tier 1 recovery warship that strips battle wreckage into immediately usable metal.', cost: cost(145, 82, 38), time: 29, factory: 'space', spaceTier: 1, hp: 320, shields: 65, range: 260, moveSpeed: 0, weapon: { label: 'Grapple Laser', damage: .7, cooldown: .45, projectiles: 2, effect: 'laser' }, ability: { kind: 'salvageArray', label: 'Salvage Array', description: 'Increases Covenant metal recovered from orbital casualties by 50% if it survives.' } },
  covenantChainFrigate: { label: 'Chain Frigate', description: 'A Tier 1 linked-cannon hunter that concentrates fire on already compromised hulls.', cost: cost(175, 108, 58), time: 36, factory: 'space', spaceTier: 1, hp: 310, shields: 55, range: 410, moveSpeed: 0, weapon: { label: 'Chain Driver', damage: 4.2, cooldown: 1.2, projectiles: 3, effect: 'kinetic' }, ability: { kind: 'focusFire', label: 'Failure Cascade', description: 'Deals 50% more damage to ships whose hull is already damaged.' } },
  covenantSurveyorSkiff: { label: 'Surveyor Skiff', description: 'A stripped-down Tier 1 reconnaissance machine built around an overclocked transit engine.', cost: cost(125, 72, 34), time: 10, factory: 'space', spaceTier: 1, hp: 250, shields: 40, range: 210, moveSpeed: 0, orbitSpeedMultiplier: 2.5, weapon: { label: 'Survey Needle', damage: .2, cooldown: .8, projectiles: 1, effect: 'kinetic' }, ability: { kind: 'reconDrive', label: 'Overclocked Survey Drive', description: 'Moves through gravity wells and phase lanes at 2.5× normal ship speed, but carries only a light defensive weapon.' } },
  covenantLockstepFrigate: { label: 'Lockstep Frigate', description: 'A Tier 1 control machine that forces hostile propulsion and weapon cycles into a slower cadence.', cost: cost(220, 145, 80), time: 44, factory: 'space', spaceTier: 1, hp: 360, shields: 60, range: 340, moveSpeed: 0, weapon: { label: 'Lockstep Pulse', damage: .32, cooldown: .8, projectiles: 2, effect: 'pulse' }, ability: { kind: 'phaseControl', label: 'Lockstep Field', description: 'Enemies inside range move and fire at 75% speed. Multiple fields stack multiplicatively.' } },
  covenantAssemblyArkII: { label: 'Assembly Ark Cruiser', description: 'Tier 2 counterpart to the Assembly Ark with twelve berths and redundant mobile machine shops.', cost: cost(330, 220, 125), time: 58, factory: 'space', spaceTier: 2, hp: 720, shields: 140, range: 220, moveSpeed: 0, weapon: { label: 'Assembly II Defense Laser', damage: .28, cooldown: .3, projectiles: 4, effect: 'laser' }, capacity: 12, requires: 'orbitalEngineering', ability: { kind: 'assemblyLine', label: 'Expanded Assembly Line', description: 'Restores 4 hull per second to nearby allied ships during orbital combat.' } },
  covenantSalvageCruiser: { label: 'Salvage Cruiser', description: 'Tier 2 counterpart to the Salvage Frigate with four grapple arrays and reinforced processing bays.', cost: cost(360, 240, 140), time: 62, factory: 'space', spaceTier: 2, hp: 640, shields: 130, range: 320, moveSpeed: 0, weapon: { label: 'Reclaimer Grapple Laser', damage: .9, cooldown: .45, projectiles: 4, effect: 'laser' }, requires: 'orbitalEngineering', ability: { kind: 'salvageArray', label: 'Cruiser Salvage Array', description: 'Increases Covenant metal recovered from orbital casualties by 50% if it survives.' } },
  covenantChainCruiser: { label: 'Chain Cruiser', description: 'Tier 2 counterpart to the Chain Frigate with five linked drivers for sustained focus fire.', cost: cost(390, 260, 155), time: 66, factory: 'space', spaceTier: 2, hp: 620, shields: 110, range: 460, moveSpeed: 0, weapon: { label: 'Chain Cruiser Driver', damage: 5, cooldown: 1.2, projectiles: 5, effect: 'kinetic' }, requires: 'orbitalEngineering', ability: { kind: 'focusFire', label: 'Cruiser Failure Cascade', description: 'Deals 50% more damage to ships whose hull is already damaged.' } },
  covenantInterdictorCruiser: { label: 'Interdictor Flak Cruiser', description: 'Tier 2 counterpart to the Interdictor Frigate with six predictive rotary mounts.', cost: cost(400, 270, 160), time: 68, factory: 'space', spaceTier: 2, hp: 680, shields: 130, range: 350, moveSpeed: 0, weapon: { label: 'Interdictor Cruiser Rotary Mount', damage: .65, cooldown: .45, projectiles: 6, effect: 'kinetic' }, requires: 'orbitalEngineering', ability: { kind: 'antiFighterCannons', label: 'Cruiser Flightpath Interdiction', description: 'Prioritizes one hostile fighter wing and deals 50% more damage to fighters.' } },
  covenantLockstepCruiser: { label: 'Lockstep Cruiser', description: 'Tier 2 counterpart to the Lockstep Frigate, imposing a cadence rigid enough to seal hostile phase gates.', cost: cost(470, 320, 190), time: 76, factory: 'space', spaceTier: 2, hp: 720, shields: 120, range: 400, moveSpeed: 0, weapon: { label: 'Lockstep Projector', damage: .48, cooldown: .8, projectiles: 4, effect: 'pulse' }, requires: 'orbitalEngineering', ability: { kind: 'phaseControl', label: 'Lockstep Interdiction', description: 'Enemies inside range move and fire at 75% speed and cannot enter a phase lane. Multiple fields stack multiplicatively.' } },
  covenantFoundryCruiser: { label: 'Foundry Cruiser', description: 'A Tier 2 industrial cruiser with stronger batteries and repair gantries for its battle group.', cost: cost(430, 300, 180), time: 68, factory: 'space', spaceTier: 2, hp: 880, shields: 140, range: 350, moveSpeed: 0, weapon: { label: 'Foundry Plasma Bank', damage: 3.2, cooldown: 1, projectiles: 4, effect: 'plasma' }, requires: 'orbitalEngineering', ability: { kind: 'foundryAura', label: 'Fleet Foundry', description: 'Restores 7 hull per second to nearby allied ships during orbital combat.' } },
  covenantFabricatorCarrier: { label: 'Fabricator Mega-Carrier', description: 'A Tier 3 modular carrier that prints attack drones to replace every machine lost around hostile hulls.', cost: cost(760, 550, 340), time: 112, factory: 'space', spaceTier: 3, hp: 1320, shields: 220, range: 350, moveSpeed: 0, weapon: { label: 'Fabricated Fighter', damage: 1.7, cooldown: .75, projectiles: 8, effect: 'drone' }, requires: 'carrierOperations', capacity: 10, fighterWing: { label: 'Fabricated Fighters', capacity: 8, rebuildTime: 14, attritionTime: 12 }, ability: { kind: 'fabricatorSwarm', label: 'Fabricator Swarm', description: 'Every fighter attack also pressures a second nearby hostile ship for 50% damage.' } },
  covenantIronclad: { label: 'Ironclad Battleship', description: 'A Tier 3 capital machine wrapped in replaceable armor blocks and heavy kinetic batteries.', cost: cost(820, 590, 370), time: 122, factory: 'space', spaceTier: 3, hp: 1750, shields: 220, range: 420, moveSpeed: 0, weapon: { label: 'Ironclad Rail Battery', damage: 9, cooldown: 1.15, projectiles: 3, effect: 'railgun' }, requires: 'capitalShips', ability: { kind: 'ironcladArmor', label: 'Layered Ironclad', description: 'Reduces all incoming damage by 25%.' } },
  covenantInterdictor: { label: 'Interdictor Flak Frigate', description: 'A mass-produced Tier 1 escort that fills predicted fighter paths with rotary cannon fire.', cost: cost(185, 115, 62), time: 38, factory: 'space', spaceTier: 1, hp: 340, shields: 65, range: 300, moveSpeed: 0, weapon: { label: 'Rotary Flak Mount', damage: .5, cooldown: .45, projectiles: 4, effect: 'kinetic' }, ability: { kind: 'antiFighterCannons', label: 'Flightpath Interdiction', description: 'Prioritizes one hostile fighter wing and deals 50% more damage to fighters.' } },
  covenantDreadforge: { label: 'Dreadforge Titan', description: 'The Covenant’s unique Tier 3 Titan, a mobile foundry built around a fortress-dismantling beam.', cost: cost(2400, 1800, 1250), time: 230, factory: 'space', spaceTier: 3, hp: 4800, shields: 900, range: 520, moveSpeed: 0, weapon: { label: 'Dreadforge Dismantler', damage: 29, cooldown: 1.2, projectiles: 3, effect: 'siege' }, requires: 'titanEngineering', ability: { kind: 'dismantlerBeam', label: 'Dismantler Beam', description: 'Deals double damage to orbital defense platforms.' } },
};
